# This is a basic workflow to help you get started with Actions

name: Heii.... selamat pagi manusia  yg cantik and menggemaskan🫶... semangat ia ngejalanin hari nyh ia..., tetap jaga kesehatan juga, klo capek boleh kok ngeluh tpi jgn lama" ia apa lagi klo dah badmood... ampun dehh😅...ayoo bahagis terus dgn hal sekecil apapun itu... makasih ia udh berjuang sampai hari ini..,klo kmu mikir gak ada yg sayang sama kmu, kmu harus tau klo Allah itu selalu senyum bangga tiap dia melihat perjuangan kmu .. jadi tetap semangat ia cantik 🫶🫶🥰


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
